{
  lib,
  config,
  inputs,
  ...
}:

################################################################################
# FACTER MODULE
################################################################################

let
  cfg = config.ft.hardware.facter;
in
{
  imports = [ inputs.nixos-facter.nixosModules.facter ];

  options.ft.hardware.facter = {
    enable = lib.mkEnableOption "nixos-facter hardware detection" // {
      description = "Imports the nixos-facter NixOS module and points it at a facter.json report committed to the host directory. Replaces hardware-configuration.nix for kernel-module and filesystem detection. Generate the report by running 'just facter' on the target machine and saving the output as hosts/<arch>/<hostname>/facter.json.";
    };

    reportPath = lib.mkOption {
      type = lib.types.path;
      description = "Path to the facter.json file generated by nixos-facter. Typically set to ./facter.json relative to the host's default.nix (pass the store path, e.g. ./facter.json in the host's imports context).";
    };
  };

  config = lib.mkIf cfg.enable {
    facter.reportPath = cfg.reportPath;
  };
}
